<?php


class CardType
{
    const IMAGE_ONLY = 'IMAGE_ONLY';
    const TEXT_ONLY = 'TEXT_ONLY';
    const BODY_WITH_CARD_NAME = 'BODY_WITH_CARD_NAME';
    const BODY_WITH_TEXT = 'BODY_WITH_TEXT';
    const BODY_WITH_IMAGES = 'BODY_WITH_TEXT';
    const HEADER_WITH_IMAGE = 'HEADER_WITH_IMAGE';
    const FOOTER_WITH_IMAGE = 'FOOTER_WITH_IMAGE';
    const HEADER_AND_FOOTER_WITH_IMAGE = 'HEADER_AND_FOOTER_WITH_IMAGE';
}
