CREATE TABLE `INGREDIENTS` (
	`INGREDIENT_ID` INT NOT NULL AUTO_INCREMENT DEFAULT '10001',
	`INGREDIENT_NAME` varchar(255) NOT NULL,
	`INGREDIENT_DESCRIPTION` varchar(5000) NOT NULL,
	PRIMARY KEY (`INGREDIENT_ID`)
);

CREATE TABLE `CATEGORIES` (
	`CATEGORY_ID` INT NOT NULL AUTO_INCREMENT DEFAULT '101',
	`CATEGORY_NAME` varchar(255) NOT NULL,
	`CATEGORY_DESCRIPTION` varchar(1000) NOT NULL,
	PRIMARY KEY (`CATEGORY_ID`)
);

CREATE TABLE `CATEGORY_INGREDIENTS` (
	`CATING_ID` INT NOT NULL AUTO_INCREMENT DEFAULT '10001',
	`CATEGORY_ID` INT,
	`INGREDIENT_ID` INT,
	PRIMARY KEY (`CATING_ID`)
);

CREATE TABLE `ACTIONS` (
	`ACTION_ID` INT NOT NULL AUTO_INCREMENT DEFAULT '101',
	`ACTION_NAME` varchar(255) NOT NULL UNIQUE,
	`ACTION_DESCRIPTION` varchar(1000) NOT NULL,
	PRIMARY KEY (`ACTION_ID`)
);

CREATE TABLE `ACTION_INGREDIENTS` (
	`ACTING_ID` INT NOT NULL AUTO_INCREMENT DEFAULT '10001',
	`ACTION_ID` INT NOT NULL,
	`INGREDIENT_ID` INT,
	PRIMARY KEY (`ACTING_ID`)
);

CREATE TABLE `CONSTRUCTORS` (
	`CONSTRUCTOR_ID` INT NOT NULL AUTO_INCREMENT DEFAULT '101',
	`CONSTRUCTOR_NAME` varchar(255) NOT NULL UNIQUE,
	`CONSTRUCTOR_DESCRIPTION` varchar(1000) NOT NULL,
	PRIMARY KEY (`CONSTRUCTOR_ID`)
);

CREATE TABLE `CONSTRUCTOR_ACTIONS` (
	`CONSACT_ID` INT NOT NULL AUTO_INCREMENT DEFAULT '10001',
	`CONSTRUCTOR_ID` INT NOT NULL,
	`ACTION_ID` INT NOT NULL,
	PRIMARY KEY (`CONSACT_ID`)
);

ALTER TABLE `CATEGORY_INGREDIENTS` ADD CONSTRAINT `CATEGORY_INGREDIENTS_fk0` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORIES`(`CATEGORY_ID`);

ALTER TABLE `CATEGORY_INGREDIENTS` ADD CONSTRAINT `CATEGORY_INGREDIENTS_fk1` FOREIGN KEY (`INGREDIENT_ID`) REFERENCES `INGREDIENTS`(`INGREDIENT_ID`);

ALTER TABLE `ACTION_INGREDIENTS` ADD CONSTRAINT `ACTION_INGREDIENTS_fk0` FOREIGN KEY (`ACTION_ID`) REFERENCES `ACTIONS`(`ACTION_ID`);

ALTER TABLE `ACTION_INGREDIENTS` ADD CONSTRAINT `ACTION_INGREDIENTS_fk1` FOREIGN KEY (`INGREDIENT_ID`) REFERENCES `INGREDIENTS`(`INGREDIENT_ID`);

ALTER TABLE `CONSTRUCTOR_ACTIONS` ADD CONSTRAINT `CONSTRUCTOR_ACTIONS_fk0` FOREIGN KEY (`CONSTRUCTOR_ID`) REFERENCES `CONSTRUCTORS`(`CONSTRUCTOR_ID`);

ALTER TABLE `CONSTRUCTOR_ACTIONS` ADD CONSTRAINT `CONSTRUCTOR_ACTIONS_fk1` FOREIGN KEY (`ACTION_ID`) REFERENCES `ACTIONS`(`ACTION_ID`);

